name: stats
version: 0.1.2
author: Adam Singer <financeCoding@gmail.com>
description: Visual Dart Performance Monitor
homepage: https://github.com/Dartist/stats.dart
environment:
  sdk: ">=1.0.0 <2.0.0"
dependencies:
  unittest: ">=0.9.0 < 0.11.0"
  browser: ">=0.9.0 < 0.11.0"
dev_dependencies:
  html5lib: '>=0.9.2 <0.10.0'
  hop: '>=0.30.0 <0.31.0'
