name: stats
description: Visual Dart Performance Monitor
version: 0.0.4
author: Adam Singer <financeCoding@gmail.com>
homepage: https://github.com/Dartist/stats.dart
dependencies:
  browser: ">=0.3.4"
  unittest: ">=0.3.4"
  bot: ">=0.12.0"