name: stats
version: 0.0.9
author: Adam Singer <financeCoding@gmail.com>
description: Visual Dart Performance Monitor
homepage: https://github.com/Dartist/stats.dart
environment:
  sdk: '>=0.4.5+1.r21094'
dependencies:
  unittest: '>=0.4.3+1'
dev_dependencies:
  html5lib: '>=0.4.1'
  browser: '>=0.4.3+1'
  hop: '>=0.20.0 <0.21.0'
