name: stats
version: 0.0.10
author: Adam Singer <financeCoding@gmail.com>
description: Visual Dart Performance Monitor
homepage: https://github.com/Dartist/stats.dart
environment:
  sdk: '>=0.4.7+5.r21658'
dependencies:
  unittest: '>=0.5.0+1'
dev_dependencies:
  html5lib: '>=0.4.3'
  browser: '>=0.5.0+1'
  hop: '>=0.21.0 <0.22.0'
